# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Todoary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Todoary

  pod 'SnapKit', '~> 5.6.0'

  pod 'Then'

  pod 'skpsmtpmessage'

  pod 'Alamofire'

  pod 'IRSticker-swift'

  pod 'StickerView'

  # firebase 
  pod 'Firebase/Analytics' # Google Analytics

  pod 'Firebase/Messaging'

  target 'TodoaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodoaryUITests' do
    # Pods for testing
  end

end
